circle_yolo_exp_1:
    experiment_name: circle_yolov8n
    model_name : yolov8n.pt
    model_config:
        name: bullet_hole_circle
        data: data/03_primary/gunshots/circle/yolov5_format/data_config.yaml
        epochs: 32
        batch: 8
        img_size: 640
        nc: 1
        names: [gunshot_hole]
        colors: [240, 230, 92]

circle_yolo_exp_2:
    experiment_name: circle_yolov8s
    model_name : yolov8s.pt
    model_config:
        name: bullet_hole_circle
        data: data/03_primary/gunshots/circle/yolov5_format/data_config.yaml
        epochs: 32
        batch: 8
        img_size: 640
        nc: 1
        names: [gunshot_hole]
        colors: [240, 230, 92]

circle_yolo_exp_3:
    experiment_name: circle_yolov5n
    model_name : yolov5n.pt
    model_config:
        name: bullet_hole_circle
        data: data/03_primary/gunshots/circle/yolov5_format/data_config.yaml
        epochs: 32
        batch: 8
        img_size: 640
        nc: 1
        names: [gunshot_hole]
        colors: [240, 230, 92]

circle_yolo_exp_4:
    experiment_name: circle_yolov5s
    model_name : yolov5s.pt
    model_config:
        name: bullet_hole_circle
        data: data/03_primary/gunshots/circle/yolov5_format/data_config.yaml
        epochs: 32
        batch: 8
        img_size: 640
        nc: 1
        names: [gunshot_hole]
        colors: [240, 230, 92]

circle_yolo_exp_5:
    experiment_name: circle_yolov9c
    model_name : rtdetr-l.pt
    model_config:
        name: bullet_hole_circle
        data: data/03_primary/gunshots/circle/yolov5_format/data_config.yaml
        epochs: 32
        batch: 8
        img_size: 640
        nc: 1
        names: [gunshot_hole]
        colors: [240, 230, 92]