detectron2:
    #
    rccn_101_conf1_v1:
        dataprep_params:
            experiment_id: "detectron2_rccn_101_conf1_v1"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            pretrained_model_config: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            num_workers: 2
            pretrained_model_weights: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            ims_per_batch: 2
            base_lr: 0.00125
            max_iter: 256
            steps: []
            batch_size_per_image: 512
            num_classes: 2
            score_thresh_test: 0.5
    #
    rccn_101_conf2_v1:
        dataprep_params:
            experiment_id: "detectron2_rccn_101_conf2_v1"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            pretrained_model_config: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            num_workers: 2
            pretrained_model_weights: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            ims_per_batch: 2
            base_lr: 0.00125
            max_iter: 512
            steps: []
            batch_size_per_image: 512
            num_classes: 2
            score_thresh_test: 0.5
    #
    rccn_101_conf3_v1:
        dataprep_params:
            experiment_id: "detectron2_rccn_101_conf3_v1"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            pretrained_model_config: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            num_workers: 2
            pretrained_model_weights: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            ims_per_batch: 2
            base_lr: 0.00125
            max_iter: 1024
            steps: []
            batch_size_per_image: 512
            num_classes: 2
            score_thresh_test: 0.5
    #
    rccn_101_conf1_v2:
        dataprep_params:
            experiment_id: "detectron2_rccn_101_conf1_v2"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v2
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            pretrained_model_config: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            num_workers: 2
            pretrained_model_weights: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
            ims_per_batch: 2
            base_lr: 0.00125
            max_iter: 256
            steps: []
            batch_size_per_image: 512
            num_classes: 2
            score_thresh_test: 0.5
    #
    mask_rccn_50_conf1_v1:
        dataprep_params:
            experiment_id: "detectron2_mask_rccn_50_conf1_v1"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            pretrained_model_config: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
            num_workers: 2
            pretrained_model_weights: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
            ims_per_batch: 2
            base_lr: 0.00125
            max_iter: 256
            steps: []
            batch_size_per_image: 512
            num_classes: 2
            score_thresh_test: 0.5
yolo:
    #
    yolov8_conf1_v1:
        dataprep_params:
            experiment_id: &yolo_experiment_id "yolov8_conf1_v1" 
            yolo_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - yolo
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            model_name : yolov8n.pt
            experiment_name: *yolo_experiment_id
            model_config:
                epochs: 128
                batch: 16
                img_size: 512
                optimizer: "auto" # Options include SGD, Adam, AdamW, NAdam, RAdam, RMSProp etc., or auto for automatic selection based on model configuration.
                lr: 0.0001
                workers: 8
                rect: True
                iou: 0.5
detr:
    detr_resnet_50_conf1_v1:
        dataprep_params:
            experiment_id: "detr_resnet_50_conf1_v1"
            coco_data:
                path:
                    - data
                    - 05_model_input
                    - gunshots
                    - coco
                    - v1
                datasets:
                    - train
                    - valid
                    - test
        fine_tuning_params:
            path:
                - data
                - 06_models
                - output
            num_workers: 2
            batch_size: 2
            lr: 0.0001
            lr_backbone: 0.0001
            weight_decay: 0.0001
            epochs: 5